.\" THIS IS A UNOFFICIAL MAN PAGE OF DOTNET"
.\" IF YOU WAN TO CONTRIBUTE YOU CAN DO IT HERE :"
.\" https://github.com/MauriceHandwerker/dotnet-man "

.TH man 1 "21.08.2023" "1.0" "DOTNET MAN PAGE"

.SH INFO
.PP 
Unofficial Man page of dotnet.

.PP 
To contribute = https://github.com/MauriceHandwerker/dotnet-man

.SH NEW PROJECT
.B dotnet new [PROJECT TYPE]

.PP
This creates a new dotnet project from the type you chose.

.SH LIST PROJECT TYPES
.B dotnet new list

.PP
To get a list of all possible project types. You can get more informations about a type
by using the following.

.B dotnet new [PROJECT TYPE] -h

.SH BUILD PROJECT
.B dotnet build

.PP 
Befor you can run a Project you need to compile/build the project.
To do it simply you just need this. 
This will give you a path with the .dll file you can run.

.SH RUN PROJECT
.B dotnet run [DLL FILE]

.PP
Before you can run your project it needs to be build.
After you build your project you can run the .dll file from the path given in the console.

.SH ADD PACKAGE
.B dotnet add package [PACKAGE NAME]

.PP
This command needs to be run inside the project folder.
With this you can add packages to the project.

.SH MORE COMMING SOON!
